name: "Check Migrations Paseo"
description: "An action to check runtime migrations"
inputs:
  github-token:
    description: "GitHub token"
    required: true
  runtime-package:
    description: "The package name of the runtime"
    required: true
  runtime-uri:
    description: "The URI of the runtime"
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download try-runtime-cli
      run: |
        curl -sL https://github.com/paritytech/try-runtime-cli/releases/download/v0.6.1/try-runtime-x86_64-unknown-linux-musl -o try-runtime
        chmod +x ./try-runtime
      shell: bash

    - name: Build ${{ inputs.runtime-package }}
      run: |
        cargo build --profile production -p ${{ inputs.runtime-package }} --features try-runtime -q --locked
      shell: bash

    - name: Check migrations
      run: |
        PACKAGE_NAME=${{ inputs.runtime-package }}
        RUNTIME_BLOB_NAME=$(echo $PACKAGE_NAME | sed 's/-/_/g').compact.compressed.wasm
        RUNTIME_BLOB_PATH=./target/production/wbuild/$PACKAGE_NAME/$RUNTIME_BLOB_NAME

        # Store the command in a variable so we can log it
        COMMAND="./try-runtime \
          --runtime $RUNTIME_BLOB_PATH \
          on-runtime-upgrade --checks=${{ inputs.checks }} \
          --disable-spec-version-check --no-weight-warnings \
          live --uri ${{ inputs.runtime-uri }}"

        # Echo the command before running it, for debugging purposes
        echo "Running command:"
        echo "$COMMAND"
        eval "$COMMAND"

      shell: bash


