[package]
authors = ["Frequency"]
description = "Substrate CLI options for Frequency node"
edition = "2021"
homepage = "https://frequency.xyz/"
license = "Apache-2.0"
name = "cli-opt"
repository = "https://github.com/LibertyDSNP/frequency/"
version = "1.6.2-rc1+polkadot0.9.36"

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
