[package]
authors = ["Frequency"]
description = "Substrate CLI options for Frequency node"
edition = "2021"
homepage = "https://frequency.xyz/"
license = "Apache-2.0"
name = "cli-opt"
repository = "https://github.com/LibertyDSNP/frequency/"
version = "1.9.0+polkadot1.1.0"

[dependencies]
clap = { workspace = true, features = ["derive"] }
