[package]
authors = ["Frequency"]
description = "Handles Utilities"
edition = "2021"
homepage = "https://frequency.xyz"
license = "Apache-2.0"
name = "handles-utils"
version = "1.6.0-rc3+polkadot0.9.36"
publish = false
repository = "https://github.com/libertyDSNP/frequency/"

[dependencies]
phf = { version = "0.11", default-features = false, features = ["macros"] }
rand = { version = "0.8.5", default-features = false, features = ["small_rng"] }
unicode-normalization = { version = "0.1.22", default-features = false }

[features]
default = ["std"]
std = []
