[workspace]
members = [
  "node",
  "node/cli",
  "node/service",
  "pallets/*",
  "runtime/common",
  "runtime/frequency",
  "runtime/frequency-rococo",
  "common/helpers",
  "common/primitives",  # needed?
  "common/signed_extensions",
]

[profile.release]
panic = "unwind"

[profile.production]
inherits = "release"
lto = true
codegen-units = 1
