[profile.release]
panic = "unwind"

[workspace]
members = [
  "node",
  "pallets/msa",
<<<<<<< HEAD
  "pallets/schemas",
=======
  "pallets/messages",
>>>>>>> main
  "runtime/*",
  "common/helpers"
]
