[build]
pre-build = [
	"apt-get update && apt-get install -y protobuf-compiler",
	"rm -rf /var/lib/apt/lists/*",
]
# [target.aarch64-unknown-linux-gnu]
# image = "ghcr.io/libertydsnp/frequency/aarch64-unknown-linux-gnu:latest"
