[package]
name = "frequency-node"
version = "0.1.0"
authors = ["Frequency Team"]
description = "Substrate node for frequency"
license = "Apache-2.0"
homepage = "https://unfinishedlabs.io/"
repository = "https://github.com/LibertyDSNP/frequency/"
edition = "2021"
build = "build.rs"

[[bin]]
name = "frequency-collator"
path = "src/main.rs"

[dependencies]
# Frequency Runtime
frequency-runtime = { path = "../runtime/frequency" }
frequency-cli = { path = "cli" }

# Substrate
sc-cli = { git = "https://github.com/paritytech/substrate", features = ["wasmtime"] , branch = "polkadot-v0.9.25" }

[build-dependencies]
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.25" }

[features]
runtime-benchmarks = [
	"frequency-runtime/runtime-benchmarks",
	"frequency-cli/runtime-benchmarks",
]
try-runtime = ["frequency-runtime/try-runtime"]
