[package]
name = "kilt-support"
authors = ["KILT <info@kilt.io>"]
documentation = "https://docs.kilt.io"
edition = "2021"
homepage = "https://kilt.io/"
license-file = "LICENSE"
description = "Shared traits and structs used across the KILT pallets"
repository = "https://github.com/KILTprotocol/kilt-node"
version = "1.11.0-dev"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# External dependencies
parity-scale-codec = {version = "3.1.5", default-features = false}
scale-info = {version = "2.2.0", default-features = false, features = [
  "derive",
]}
log = {version = "0.4.17", default-features = false}

# Substrate dependencies
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.36" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.36" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.36" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.36" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.36" }

# std dependencies
serde = {version = "1.0.145", optional = true, features = ["derive"]}

[features]
default = ["std"]
mock = []
runtime-benchmarks = [
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
]
std = [
  "frame-support/std",
  "frame-system/std",
  "parity-scale-codec/std",
  "scale-info/std",
  "serde",
  "sp-core/std",
  "sp-runtime/std",
  "sp-std/std",
]
try-runtime = [
  "frame-support/try-runtime",
]
