[package]
authors = ["MRC Team"]
description = "A package that defines common helper modules used in MRC"
edition = "2021"
homepage = "https://unfinishedlabs.io/"
license = "Apache-2.0"
name = 'common-helpers'
publish = false
repository = "https://github.com/liberty30/mrc/"
version = "0.1.0"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = {package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"]}
apache-avro = { git = "https://github.com/apache/avro", features = ["snappy"] }
chrono = "0.4"
clap = { version = "3", features = ["derive"] }
egg-mode-extras = "0.2.1"
log = "0.4"
serde_json = { version = "1", features = ["preserve_order"] }
simplelog = "0.12"
thiserror = "1"

[dev-dependencies]
proptest = "1.0"

[features]
default = ['std']
std = [
  'codec/std',
]
