[package]
authors = ["MRC Team"]
description = "A package that defines common helper modules used in MRC"
edition = "2021"
homepage = "https://unfinishedlabs.io/"
license = "Apache-2.0"
name = 'common-helpers'
publish = false
repository = "https://github.com/liberty30/mrc/"
version = "0.1.0"

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
apache-avro = { features = ["snappy"], version ="0.0.1" }
thiserror = "1"
sha2 = "0.10.2"

[dev-dependencies]
proptest = "1.0"

[features]
default = ['std']
std = [
]
