# .github/workflows/check-migrations-on-paseo.yml

name: Check Migrations on Paseo

on:
  pull_request_target:
    types:
      - labeled

jobs:
  check-migrations:
    if: contains(github.event.pull_request.labels.*.name, 'paseo-migration')
    name: Check Migrations on Paseo
    continue-on-error: false
    runs-on: ubicloud-standard-8
    container: ghcr.io/frequency-chain/frequency/ci-base-image:1.3.1
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Run Check Migrations Action
        uses: ./.github/workflows/common/try-runtime-migrations
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          runtime-package: "frequency-runtime"
          runtime-uri: "wss://0.rpc.testnet.amplica.io:443"
