name: Create Upgrade Issue for New Polkadot Release
on:
  workflow_dispatch:
  push:
    branches:
      - ci/latest-polkadot-full-release
    paths:
      - .github/.latest-polkadot-full-release.txt
permissions:
  issues: write
env:
  RELEASE_PAGE_PREFIX_URL: https://github.com/paritytech/polkadot-sdk/releases
  RELEASE_TRACK_FILENAME: .github/.latest-polkadot-full-release.txt
jobs:
  create-issue:
    runs-on: ubuntu-22.04
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4
      - name: Set Env Vars
        run: |
          release_version=$(cat ${{env.RELEASE_TRACK_FILENAME}})
          echo "NEW_POLKADOT_RELEASE_VERSION=$release_version" >> $GITHUB_ENV
      - name: Create GitHub Issue
        uses: JasonEtco/create-an-issue@e27dddc79c92bc6e4562f268fffa5ed752639abd
        # Check if release starts with p
        if: ${{ startsWith(env.NEW_POLKADOT_RELEASE_VERSION, 'p') }}
        with:
          filename: .github/issues/new-polkadot-release.template.md
