name: Release
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # ex. v0.29.9
      - "v[0-9]+.[0-9]+.[0-9]+-[0-9]+" # ex. v0.29.9-1
      - "v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+" # ex. v0.29.9-1-rc1
env:
  RUST_TOOLCHAIN: nightly-2022-09-22 # Update this when updating the Rust toolchain
  RELEASE_VERSION: ${{github.ref_name}}

jobs:
  build-binaries:
    name: Build ${{matrix.arch}} Binary for ${{matrix.network}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        network: [rococo]
        include:
          - network: rococo
            spec: frequency-rococo-testnet
            build-profile: production
          - os: ubuntu-latest
            arch: amd64
          - os: macos-latest
            arch: arm64
    runs-on: ${{matrix.os}}
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      # # Keep it. Let's you skip full binary builds during development.
      # - name: Cache Binary
      #   id: cache-binary
      #   uses: actions/cache@v3
      #   with:
      #     path: target/${{matrix.build-profile}}/frequency
      #     key: ${{runner.os}}-${{matrix.network}}-${{matrix.arch}}-${{env.RELEASE_VERSION}}
      - name: Cache Dependencies
        if: steps.cache-binary.outputs.cache-hit != 'true'
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{env.RUST_TOOLCHAIN}}
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal
          target: wasm32-unknown-unknown
      - name: Compile for ${{matrix.network}}
        if: steps.cache-binary.outputs.cache-hit != 'true'
        run: |
          CARGO_INCREMENTAL=0 cargo build \
            --locked \
            --features ${{matrix.spec}} \
            --profile ${{matrix.build-profile}}
      - name: Run Sanity Checks
        run: |
          file ./target/${{matrix.build-profile}}/frequency && \
            ./target/${{matrix.build-profile}}/frequency --version
      - name: Archive Artifact
        run: |
          tar -cvf frequency-binary-${{matrix.network}}-${{env.RELEASE_VERSION}}.${{matrix.arch}}.tar \
            ./target/${{matrix.build-profile}}/frequency
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-${{github.run_id}}
          path: frequency-binary-${{matrix.network}}-${{env.RELEASE_VERSION}}.${{matrix.arch}}.tar
          if-no-files-found: error

  build-wasm:
    name: Build Deterministic WASM for ${{matrix.network}}
    strategy:
      matrix:
        network: [rococo]
        include:
          - network: rococo
            build-profile: production
            package: frequency-rococo-runtime
            runtime-dir: runtime/frequency-rococo
            wasm-file-name-prefix: frequency_rococo_runtime
    env:
      SRT_TOOL_VERSION: "1.62.0"
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Build Deterministic WASM with srtool
        run: |
          docker run --rm -e PACKAGE=${{matrix.package}} \
            -e RUNTIME_DIR=${{matrix.runtime-dir}} \
            -e PROFILE=${{matrix.build-profile}} \
            -e BUILD_OPTS="--features on-chain-release-build,no-metadata-docs" \
            -v $PWD:/build \
            -v /tmp/cargo:/cargo-home paritytech/srtool:$SRT_TOOL_VERSION build
      - name: Create Tarball
        run: |
          tar -cvf frequency-wasm-${{matrix.network}}-${{env.RELEASE_VERSION}}.tar \
            ./${{matrix.runtime-dir}}/target/srtool/${{matrix.build-profile}}/wbuild/${{matrix.package}}/${{matrix.wasm-file-name-prefix}}.compact.compressed.wasm \
            ./${{matrix.runtime-dir}}/target/srtool/${{matrix.build-profile}}/wbuild/${{matrix.package}}/${{matrix.wasm-file-name-prefix}}.compact.wasm \
            ./${{matrix.runtime-dir}}/target/srtool/${{matrix.build-profile}}/wbuild/${{matrix.package}}/${{matrix.wasm-file-name-prefix}}.wasm
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-${{github.run_id}}
          path: frequency-wasm-${{matrix.network}}-${{env.RELEASE_VERSION}}.tar
          if-no-files-found: error

  wait-for-all-builds:
    needs: [build-binaries]
    name: Wait for All Builds to Finish
    runs-on: ubuntu-latest
    steps:
      - name: Proceed Forward
        run: echo "All build jobs have finished, proceeding with the release"

  release-artifacts:
    needs: wait-for-all-builds
    name: Release Built Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Download Binary Artifacts
        id: download
        uses: actions/download-artifact@v3
        with:
          name: artifacts-${{github.run_id}}
          path: .
      - name: Upload Binary Artifact to Release Page
        uses: softprops/action-gh-release@v1
        with:
          files: "*.tar"

  release-node-images:
    needs: wait-for-all-builds
    name: Release ${{matrix.arch}} Node Docker Image for ${{matrix.network}}
    strategy:
      matrix:
        arch: [amd64]
        network: [rococo]
        include:
          - network: rococo
            build-profile: production
          - arch: amd64
            docker-platform: linux/amd64
    env:
      DOCKER_HUB_PROFILE: frequencychain
      IMAGE_NAME: parachain-node
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3
      - name: Download Binary Artifacts
        id: download
        uses: actions/download-artifact@v3
        with:
          name: artifacts-${{github.run_id}}
          path: .
      - name: Extract Binary
        run: |
          tar -xvf frequency-binary-${{matrix.network}}-${{env.RELEASE_VERSION}}.${{matrix.arch}}.tar
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{matrix.arch}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME_FC}}
          password: ${{secrets.DOCKERHUB_TOKEN_FC}}
      - name: Build and Push Parachain Image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: ${{matrix.docker-platform}}
          push: true
          file: ./docker/${{env.IMAGE_NAME}}.dockerfile
          tags: ${{env.DOCKER_HUB_PROFILE}}/${{env.IMAGE_NAME}}-${{matrix.network}}:${{env.RELEASE_VERSION}}
